services:
  # PostgreSQL Service
  postgres:
    image: postgres:13
    container_name: tip-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=tip_pwd
      - POSTGRES_DB=tip
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tip-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Airflow Initialization (runs once)
  airflow-init:
    image: apache/airflow:2.6.0
    container_name: tip-airflow-init
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:tip_pwd@postgres:5432/tip
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./Data:/opt/airflow/Data
      - ./logs:/opt/airflow/logs
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      bash -c "pip install --no-cache-dir beautifulsoup4 requests selenium psycopg2-binary pandas numpy &&
               airflow db init &&
               airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com"
    networks:
      - tip-network

  # Airflow Webserver
  airflow-webserver:
    image: apache/airflow:2.6.0
    container_name: tip-airflow-webserver
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:tip_pwd@postgres:5432/tip
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
    depends_on:
      - airflow-init
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./Data:/opt/airflow/Data
      - ./logs:/opt/airflow/logs
    command: >
      bash -c "pip install --no-cache-dir beautifulsoup4 requests selenium psycopg2-binary pandas numpy &&
               airflow webserver"
    networks:
      - tip-network
    restart: unless-stopped

  # Airflow Scheduler
  airflow-scheduler:
    image: apache/airflow:2.6.0
    container_name: tip-airflow-scheduler
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:tip_pwd@postgres:5432/tip
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
    depends_on:
      - airflow-init
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./Data:/opt/airflow/Data
      - ./logs:/opt/airflow/logs
    command: >
      bash -c "pip install --no-cache-dir beautifulsoup4 requests selenium psycopg2-binary pandas numpy &&
               airflow scheduler"
    networks:
      - tip-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  tip-network:
    driver: bridge